### ISSUE TITLE
crash and stuck on saving world

### ISSUE THREAD

**Issue by Gongillioning** [Sumandora/tarasande#16]
when i tried the dev build, there was a chance that when i left a singleplayer world it would freeze on Saving world, when i tried relaunching mc, it would be frozen on a black screen and i had to Ctrl Alt Del, close it, and then relaunch MC with fullscreen set to false in the options.txt file.

after that i tried 1.20.3, it worked fine on everything but when i entered a server and tried to open the ESP description, it froze, shrunk the screen and crashed, after i tried relaunching the same thing happened with the black screen, and i had to do same process.

**Comment by Sumandora** [comment]
Thanks for reporting the issue. However, without more info, it's hard to determine the cause. It could be due to outdated graphics drivers, insufficient RAM, or other software conflicts. It's also possible that your memory is faulty.

To help you better, please provide crash logs and error messages and roll out any other potential causes.

Please also note that there is no support given for older Minecraft versions as these releases are just archives of the last version of the modification that worked with them. They are not actively maintained.

**Comment by Sumandora** [comment]
Closing as stale.
